// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8TWVKltgWIcJZfa6p3unp4VzWzh1Bb14',
    appId: '1:692907996190:web:13f781904faa695f9caa0f',
    messagingSenderId: '692907996190',
    projectId: 'chat-app-94e7f',
    authDomain: 'chat-app-94e7f.firebaseapp.com',
    storageBucket: 'chat-app-94e7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmv8sYuojR8rSAIV1CgqTCJThVSFOyI9o',
    appId: '1:692907996190:android:cd8e929f79b5557e9caa0f',
    messagingSenderId: '692907996190',
    projectId: 'chat-app-94e7f',
    storageBucket: 'chat-app-94e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbXq-MYQwpjw_u7pk0vCYmqPA3RaMEtP0',
    appId: '1:692907996190:ios:9889b60785edd4069caa0f',
    messagingSenderId: '692907996190',
    projectId: 'chat-app-94e7f',
    storageBucket: 'chat-app-94e7f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbXq-MYQwpjw_u7pk0vCYmqPA3RaMEtP0',
    appId: '1:692907996190:ios:0e3d63359664d0e09caa0f',
    messagingSenderId: '692907996190',
    projectId: 'chat-app-94e7f',
    storageBucket: 'chat-app-94e7f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
